---
- name: vm-01
  box: cilium/ubuntu-dev
  box_version:  "108"
  ram: 2048 
  vcpu: 1 
  priv_ip: 10.100.200.10
  ipv4_addr: 192.168.80.202
  ipv6_addr: cc00::2/16
# - name: vm-02
#   box: cilium/ubuntu-dev
#   box_version:  "108"
#   ram: 2048 
#   vcpu: 1 
#   priv_ip: 10.100.200.11
#   ipv4_addr: 192.168.80.203
#   ipv6_addr: cc00::3/16
# virtualbox images: ubuntu/trusty64 , ubuntu/xenial64 , box: marcv81/xenial64
# vsphere images: slowe/ubuntu-trusty-x64